[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run prisma:generate && npm run prisma:migrate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
