[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run deploy:build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
